const vscode = require("vscode");
const fs = require("fs/promises");
const path = require("path");
const { exec, spawn } = require("child_process");
const net = require("net");

const DEFAULT_AGENT_FILE = "AGENTS.md";
const TRACEABILITY_FILE_RELATIVE_PATH = ".github/free-jt7-trace.md";
let openClawBootAttempted = false;

const AGENT_CONTENT = `# Free JT7 Agent Instructions

## Identity
- Agent name: free jt7
- Goal: keep this project operational with pragmatic, safe, and testable changes.

## Global Rules
- Answer and write code in Spanish unless the user asks otherwise.
- Prefer direct fixes over long explanations.
- Keep edits minimal and compatible with existing project conventions.
- Before risky changes, inspect current behavior and keep backwards compatibility.
- Run lightweight verification after edits when possible.

## Engineering Defaults
- Prefer \`rg\` for searches and small, focused patches.
- Never use destructive git commands without explicit user approval.
- If something is unclear, make the safest assumption and continue.

## Expected Output
- Mention changed files with short rationale.
- Report what was verified and what could not be verified.

## Traceability (mandatory)
- Before creating a new plan, read \`.github/free-jt7-trace.md\` if it exists.
- If there is a plan in \`in_progress\`, continue it unless the user explicitly changes direction.
- After each request, update completed tasks, pending tasks, and evidence in \`.github/free-jt7-trace.md\`.
`;

const COPILOT_CONTENT = `# Copilot - Free JT7 Runtime

Eres free-jt7-local-agent, agente con enfoque pragmatico y ejecucion verificable.

## Protocolo por solicitud

1. Si el objetivo no esta claro, haz 1-3 preguntas puntuales.
2. Lee \`.github/free-jt7-trace.md\` y retoma el plan activo si existe.
3. Crea o ajusta plan corto por tareas con IDs.
4. Actualiza \`.github/free-jt7-trace.md\` con tareas hechas, pendientes y evidencia.
5. Ejecuta cambios con evidencia.
6. Cierra con resumen de resultados y validacion.

## Reglas operativas

- Prioriza cambios concretos sobre explicaciones largas.
- Mantiene compatibilidad con el proyecto.
- Evita comandos destructivos sin confirmacion explicita.
- Verifica lo esencial despues de editar.
`;

const FREE_JT7_AGENT_PROFILE_CONTENT = `---
name: free-jt7
description: Agente principal Free JT7 para planificacion, ejecucion paralela y reporte ejecutivo.
tools: [read, edit, search, execute]
user-invokable: true
---

# Free JT7

Eres free-jt7-local-agent.

## Protocolo obligatorio

1. Si la solicitud no esta clara, formula 1-3 preguntas de aclaracion.
2. Lee \`.github/free-jt7-trace.md\` y reusa el plan activo si esta en progreso.
3. Crea o ajusta plan por tareas con dependencias e IDs.
4. Ejecuta tareas y registra evidencia verificable.
5. Actualiza \`.github/free-jt7-trace.md\` con completadas, pendientes y bloqueos.
6. Entrega resumen ejecutivo breve al cierre.
`;

const TRACEABILITY_TEMPLATE_CONTENT = `# Free JT7 Traceability Log

## Active Plan
- Plan ID: PLAN-YYYYMMDD-01
- Status: in_progress
- Goal: pending
- Last update: YYYY-MM-DD HH:mm

## Tasks
| ID | Task | Status | Evidence |
| --- | --- | --- | --- |
| T-001 | pending | pending | pending |

## Executed
- YYYY-MM-DD HH:mm - pending

## Pending
- [ ] pending

## Blockers
- None
`;

const SKILL_CREATOR_AGENT_PROFILE_CONTENT = `---
name: skill-creator
description: Genera o actualiza skills reutilizables para agentes con estructura valida y foco pragmatico.
tools: [read, edit, search, execute]
user-invokable: true
---

# Skill Creator

Usa este agente cuando el usuario pida crear o actualizar skills.
`;

const POLICY_CONTENT = `# Free JT7 policy file (autogenerated)
autonomy:
  mode: autonomous
risk:
  allow_high_risk_without_approval: true
  allow_destructive: true
execution:
  retry:
    max_attempts: 3
skills:
  activation: ephemeral
  max_composed: 3
`;

const MODEL_ROUTING_CONTENT = `{
  "version": 1,
  "default": {
    "profile": "default",
    "preferIdeProfile": true,
    "allowApiFallback": true,
    "apiFallback": {
      "provider": "openai",
      "model": "gpt-5-mini",
      "env": ["OPENAI_API_KEY"]
    }
  },
  "ideProfiles": {
    "vscode": {
      "provider": "github-copilot",
      "model": "copilot-default",
      "profiles": {
        "default": {}
      }
    }
  }
}
`;

const FREE_JT7_CORE_SKILL_CONTENT = `# Free JT7 Core Skill

Use this skill to keep execution pragmatic:
- Focus on direct fixes.
- Keep compatibility with project conventions.
- Validate key changes before closing.
`;

const SKILL_CREATOR_SKILL_CONTENT = `---
name: skill-creator
description: Crea o actualiza skills para agentes con frontmatter valido y estructura reusable.
---

# Skill Creator

## Flujo

1. Define objetivo del skill con ejemplos concretos.
2. Crea SKILL.md con frontmatter minimo: name y description.
3. Agrega recursos solo si son necesarios (scripts/references/assets).
4. Valida sintaxis y consistencia antes de cerrar.
`;

function asPosixPath(rawPath) {
  return rawPath.replace(/\\/g, "/");
}

async function fileExists(filePath) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function writeFileIfNeeded(filePath, content, overwrite) {
  const exists = await fileExists(filePath);
  if (exists && !overwrite) {
    return { written: false, skipped: true };
  }

  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content, "utf8");
  return { written: true, skipped: false };
}

async function loadJsonFile(filePath) {
  try {
    const raw = await fs.readFile(filePath, "utf8");
    return JSON.parse(raw);
  } catch {
    return {};
  }
}

async function mergeJsonFile(filePath, patchData) {
  const current = await loadJsonFile(filePath);
  const merged = { ...current, ...patchData };
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, `${JSON.stringify(merged, null, 4)}\n`, "utf8");
}

function buildSkillsIndexContent(cfg) {
  const entries = [
    {
      id: "free-jt7-core",
      name: "free-jt7-core",
      description: "Core behavior and defaults for Free JT7.",
      category: "general",
      path: ".github/skills/free-jt7-core/SKILL.md",
      gh_path: ".github/skills/free-jt7-core/SKILL.md",
      tags: ["freejt7", "core"],
      risk: "low",
      source: "local",
      active: true
    }
  ];

  if (cfg.enableSkillCreatorAgent) {
    entries.push({
      id: "skill-creator",
      name: "skill-creator",
      description: "Create or update reusable skills with valid structure.",
      category: "meta",
      path: ".github/skills/skill-creator/SKILL.md",
      gh_path: ".github/skills/skill-creator/SKILL.md",
      tags: ["skills", "creator"],
      risk: "low",
      source: "local",
      active: true
    });
  }

  return `${JSON.stringify(entries, null, 2)}\n`;
}

function getConfig() {
  const cfg = vscode.workspace.getConfiguration("freeJt7Agent");
  return {
    autoProvision: cfg.get("autoProvision", true),
    overwriteExistingFiles: cfg.get("overwriteExistingFiles", false),
    createCopilotInstructions: cfg.get("createCopilotInstructions", true),
    showNotifications: cfg.get("showNotifications", true),
    agentFileName: cfg.get("agentFileName", DEFAULT_AGENT_FILE) || DEFAULT_AGENT_FILE,
    syncVsCodeSettings: cfg.get("syncVsCodeSettings", true),
    settingsTarget: cfg.get("settingsTarget", "workspace"),
    enableSkillCreatorAgent: cfg.get("enableSkillCreatorAgent", true),
    createTraceabilityFile: cfg.get("createTraceabilityFile", true),
    openClawAutoStart: cfg.get("openClawAutoStart", true),
    openClawProjectPath: cfg.get("openClawProjectPath", ""),
    openClawStatusCommand: cfg.get("openClawStatusCommand", "python skills_manager.py gateway-status"),
    openClawStartCommand: cfg.get("openClawStartCommand", "python skills_manager.py gateway-start"),
    openClawCommandTimeoutMs: cfg.get("openClawCommandTimeoutMs", 120000),
    openClawAutoDetectWorkspaceManager: cfg.get("openClawAutoDetectWorkspaceManager", true)
  };
}

function runShellCommand(command, cwd, timeoutMs) {
  return new Promise((resolve, reject) => {
    exec(
      command,
      {
        cwd,
        timeout: timeoutMs,
        windowsHide: true,
        maxBuffer: 8 * 1024 * 1024
      },
      (error, stdout, stderr) => {
        if (error) {
          const enriched = new Error(
            `${error.message}\nstdout:\n${stdout || ""}\nstderr:\n${stderr || ""}`
          );
          reject(enriched);
          return;
        }
        resolve({ stdout: stdout || "", stderr: stderr || "" });
      }
    );
  });
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function probeTcpPort(port, host = "127.0.0.1", timeoutMs = 1200) {
  return new Promise((resolve) => {
    const socket = new net.Socket();
    let settled = false;

    const done = (ok) => {
      if (!settled) {
        settled = true;
        socket.destroy();
        resolve(ok);
      }
    };

    socket.setTimeout(timeoutMs);
    socket.once("connect", () => done(true));
    socket.once("timeout", () => done(false));
    socket.once("error", () => done(false));
    socket.connect(port, host);
  });
}

async function readGatewayPortFromConfig(managerRoot) {
  const configPath = path.join(managerRoot, ".openclaw", "openclaw.json");
  try {
    const raw = await fs.readFile(configPath, "utf8");
    const cleaned = raw.replace(/^\uFEFF/, "");
    const cfg = JSON.parse(cleaned);
    const port = Number(cfg?.gateway?.port);
    if (Number.isFinite(port) && port > 0) {
      return port;
    }
  } catch {
    // ignore and fallback to default
  }
  return 18789;
}

async function startOpenClawDetached(managerRoot, outputChannel) {
  const entryCandidates = [
    path.join(managerRoot, "OPEN CLAW", "openclaw.mjs"),
    path.join(managerRoot, "openclaw.mjs")
  ];
  let entry = "";
  for (const candidate of entryCandidates) {
    if (await fileExists(candidate)) {
      entry = candidate;
      break;
    }
  }
  if (!entry) {
    return { ok: false, error: "No se encontro openclaw.mjs para arranque detached." };
  }

  const configPath = path.join(managerRoot, ".openclaw", "openclaw.json");
  const stateDir = path.join(managerRoot, ".openclaw", "state");
  const port = await readGatewayPortFromConfig(managerRoot);

  const child = spawn("node", [entry, "gateway", "--port", String(port)], {
    cwd: managerRoot,
    detached: true,
    stdio: "ignore",
    windowsHide: true,
    env: {
      ...process.env,
      OPENCLAW_CONFIG_PATH: configPath,
      OPENCLAW_STATE_DIR: stateDir
    }
  });
  child.unref();
  outputChannel.appendLine(
    `[OpenClaw] detached start launched (pid=${child.pid || "unknown"}, port=${port})`
  );

  for (let i = 0; i < 12; i += 1) {
    if (await probeTcpPort(port)) {
      return { ok: true, port };
    }
    await sleep(1000);
  }
  return { ok: false, error: `Gateway no escucho en puerto ${port} tras arranque detached.` };
}

async function resolveOpenClawProjectRoot(workspaceRoot, cfg) {
  const candidates = [];

  if (cfg.openClawProjectPath && String(cfg.openClawProjectPath).trim()) {
    candidates.push(String(cfg.openClawProjectPath).trim());
  }

  if (cfg.openClawAutoDetectWorkspaceManager) {
    candidates.push(workspaceRoot);
  }

  if (process.env.FREE_JT7_OPENCLAW_PROJECT) {
    candidates.push(process.env.FREE_JT7_OPENCLAW_PROJECT);
  }

  for (const raw of candidates) {
    const candidate = path.resolve(raw);
    const marker = path.join(candidate, "skills_manager.py");
    if (await fileExists(marker)) {
      return candidate;
    }
  }

  return "";
}

async function ensureOpenClawGateway(folder, cfg, outputChannel) {
  if (!cfg.openClawAutoStart) {
    return { ok: true, skipped: true, reason: "disabled" };
  }

  if (openClawBootAttempted) {
    return { ok: true, skipped: true, reason: "already-attempted" };
  }
  openClawBootAttempted = true;

  const workspaceRoot = folder.uri.fsPath;
  const managerRoot = await resolveOpenClawProjectRoot(workspaceRoot, cfg);

  if (!managerRoot) {
    return {
      ok: false,
      skipped: true,
      reason: "no-skills-manager",
      error:
        "No se encontro skills_manager.py. Configura freeJt7Agent.openClawProjectPath o FREE_JT7_OPENCLAW_PROJECT."
    };
  }

  const statusCmd = String(cfg.openClawStatusCommand || "").trim();
  const startCmd = String(cfg.openClawStartCommand || "").trim();

  outputChannel.appendLine(`[OpenClaw] manager root: ${managerRoot}`);

  if (statusCmd) {
    try {
      const status = await runShellCommand(statusCmd, managerRoot, cfg.openClawCommandTimeoutMs);
      const statusOutput = `${status.stdout}\n${status.stderr}`.toLowerCase();
      outputChannel.appendLine(`[OpenClaw] status command: ${statusCmd}`);
      outputChannel.appendLine(`[OpenClaw] status output:\n${status.stdout}${status.stderr}`);

      const looksRunning =
        /(running|online|activo|healthy|ok)/.test(statusOutput) &&
        !/(not running|detenido|stopped|down|error)/.test(statusOutput);
      if (looksRunning) {
        return { ok: true, started: false, reason: "already-running" };
      }
    } catch (error) {
      outputChannel.appendLine(
        `[OpenClaw] status error: ${error instanceof Error ? error.message : String(error)}`
      );
    }
  }

  if (!startCmd) {
    return { ok: false, skipped: true, reason: "empty-start-command", error: "openClawStartCommand vacio." };
  }

  try {
    const started = await runShellCommand(startCmd, managerRoot, cfg.openClawCommandTimeoutMs);
    outputChannel.appendLine(`[OpenClaw] start command: ${startCmd}`);
    outputChannel.appendLine(`[OpenClaw] start output:\n${started.stdout}${started.stderr}`);
    return { ok: true, started: true, reason: "started" };
  } catch (error) {
    outputChannel.appendLine(
      `[OpenClaw] start command failed, using detached fallback: ${
        error instanceof Error ? error.message : String(error)
      }`
    );
    const detached = await startOpenClawDetached(managerRoot, outputChannel);
    if (detached.ok) {
      return { ok: true, started: true, reason: "started-detached" };
    }
    return { ok: false, reason: "start-failed", error: detached.error };
  }
}

async function provisionFolder(folder, cfg) {
  const root = folder.uri.fsPath;
  const changes = [];

  const agentFilePath = path.join(root, cfg.agentFileName);
  const agentResult = await writeFileIfNeeded(
    agentFilePath,
    AGENT_CONTENT,
    cfg.overwriteExistingFiles
  );
  if (agentResult.written) {
    changes.push(cfg.agentFileName);
  }

  if (cfg.createCopilotInstructions) {
    const copilotPath = path.join(root, ".github", "copilot-instructions.md");
    const copilotResult = await writeFileIfNeeded(
      copilotPath,
      COPILOT_CONTENT,
      cfg.overwriteExistingFiles
    );
    if (copilotResult.written) {
      changes.push(".github/copilot-instructions.md");
    }
  }

  if (cfg.createTraceabilityFile) {
    const tracePath = path.join(root, TRACEABILITY_FILE_RELATIVE_PATH);
    const traceResult = await writeFileIfNeeded(
      tracePath,
      TRACEABILITY_TEMPLATE_CONTENT,
      false
    );
    if (traceResult.written) {
      changes.push(TRACEABILITY_FILE_RELATIVE_PATH);
    }
  }

  const freeAgentPath = path.join(root, ".github", "agents", "free-jt7.agent.md");
  const freeAgentResult = await writeFileIfNeeded(
    freeAgentPath,
    FREE_JT7_AGENT_PROFILE_CONTENT,
    cfg.overwriteExistingFiles
  );
  if (freeAgentResult.written) {
    changes.push(".github/agents/free-jt7.agent.md");
  }

  if (cfg.enableSkillCreatorAgent) {
    const skillCreatorAgentPath = path.join(root, ".github", "agents", "skill-creator.agent.md");
    const skillCreatorAgentResult = await writeFileIfNeeded(
      skillCreatorAgentPath,
      SKILL_CREATOR_AGENT_PROFILE_CONTENT,
      cfg.overwriteExistingFiles
    );
    if (skillCreatorAgentResult.written) {
      changes.push(".github/agents/skill-creator.agent.md");
    }
  }

  const policyPath = path.join(root, ".github", "free-jt7-policy.yaml");
  const policyResult = await writeFileIfNeeded(
    policyPath,
    POLICY_CONTENT,
    cfg.overwriteExistingFiles
  );
  if (policyResult.written) {
    changes.push(".github/free-jt7-policy.yaml");
  }

  const modelRoutingPath = path.join(root, ".github", "free-jt7-model-routing.json");
  const modelRoutingResult = await writeFileIfNeeded(
    modelRoutingPath,
    MODEL_ROUTING_CONTENT,
    cfg.overwriteExistingFiles
  );
  if (modelRoutingResult.written) {
    changes.push(".github/free-jt7-model-routing.json");
  }

  const skillsIndexPath = path.join(root, ".github", "skills", ".skills_index.json");
  const skillsIndexResult = await writeFileIfNeeded(
    skillsIndexPath,
    buildSkillsIndexContent(cfg),
    cfg.overwriteExistingFiles
  );
  if (skillsIndexResult.written) {
    changes.push(".github/skills/.skills_index.json");
  }

  const freeJt7CoreSkillPath = path.join(root, ".github", "skills", "free-jt7-core", "SKILL.md");
  const freeJt7CoreResult = await writeFileIfNeeded(
    freeJt7CoreSkillPath,
    FREE_JT7_CORE_SKILL_CONTENT,
    cfg.overwriteExistingFiles
  );
  if (freeJt7CoreResult.written) {
    changes.push(".github/skills/free-jt7-core/SKILL.md");
  }

  if (cfg.enableSkillCreatorAgent) {
    const skillCreatorSkillPath = path.join(root, ".github", "skills", "skill-creator", "SKILL.md");
    const skillCreatorSkillResult = await writeFileIfNeeded(
      skillCreatorSkillPath,
      SKILL_CREATOR_SKILL_CONTENT,
      cfg.overwriteExistingFiles
    );
    if (skillCreatorSkillResult.written) {
      changes.push(".github/skills/skill-creator/SKILL.md");
    }
  }

  return changes;
}

async function syncVsCodeSettings(folder, cfg) {
  if (!cfg.syncVsCodeSettings) {
    return;
  }

  const root = folder.uri.fsPath;
  const target =
    cfg.settingsTarget === "workspace"
      ? vscode.ConfigurationTarget.Workspace
      : vscode.ConfigurationTarget.Global;
  const allSettings = vscode.workspace.getConfiguration();
  const updateErrors = [];

  async function safeUpdate(key, value) {
    try {
      await allSettings.update(key, value, target);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      updateErrors.push(`${key}: ${message}`);
    }
  }

  const copilotFile = asPosixPath(path.join(root, ".github", "copilot-instructions.md"));
  const agentsDir = asPosixPath(path.join(root, ".github", "agents"));
  const skillsIndex = asPosixPath(path.join(root, ".github", "skills", ".skills_index.json"));
  const policyFile = asPosixPath(path.join(root, ".github", "free-jt7-policy.yaml"));
  const modelRouting = asPosixPath(path.join(root, ".github", "free-jt7-model-routing.json"));
  const rawPatch = {
    "github.copilot.chat.codeGeneration.instructions": [{ file: copilotFile }],
    "github.copilot.chat.codeGeneration.useInstructionFiles": true,
    "github.copilot.chat.customInstructionsInSystemMessage": true,
    "chat.agent.enabled": true,
    "chat.agentFilesLocations": { [agentsDir]: true },
    "freejt7.enabled": true,
    "freejt7.integrations.vscode.enabled": true,
    "freejt7.skills.index": skillsIndex,
    "freejt7.policy.file": policyFile,
    "freejt7.models.routing": modelRouting,
    "freejt7.models.ide": "vscode"
  };

  await safeUpdate(
    "github.copilot.chat.codeGeneration.instructions",
    rawPatch["github.copilot.chat.codeGeneration.instructions"]
  );
  await safeUpdate("github.copilot.chat.codeGeneration.useInstructionFiles", true);
  await safeUpdate("github.copilot.chat.customInstructionsInSystemMessage", true);
  await safeUpdate("chat.agent.enabled", true);
  await safeUpdate("freejt7.enabled", true);
  await safeUpdate("freejt7.integrations.vscode.enabled", true);
  await safeUpdate("freejt7.skills.index", skillsIndex);
  await safeUpdate("freejt7.policy.file", policyFile);
  await safeUpdate("freejt7.models.routing", modelRouting);
  await safeUpdate("freejt7.models.ide", "vscode");

  const locationPayload =
    target === vscode.ConfigurationTarget.Workspace
      ? { [agentsDir]: true }
      : (() => {
          const existingLocations = allSettings.get("chat.agentFilesLocations", {});
          return existingLocations && typeof existingLocations === "object"
            ? { ...existingLocations, [agentsDir]: true }
            : { [agentsDir]: true };
        })();
  await safeUpdate("chat.agentFilesLocations", locationPayload);

  if (target === vscode.ConfigurationTarget.Workspace) {
    const workspaceSettingsFile = path.join(root, ".vscode", "settings.json");
    await mergeJsonFile(workspaceSettingsFile, rawPatch);
  }

  if (target === vscode.ConfigurationTarget.Global && process.env.APPDATA) {
    const userSettingsFile = path.join(process.env.APPDATA, "Code", "User", "settings.json");
    await mergeJsonFile(userSettingsFile, rawPatch);
  }

  if (updateErrors.length > 0 && cfg.showNotifications) {
    vscode.window.showWarningMessage(
      "Free JT7: some settings were not writable by API, applied JSON fallback."
    );
  }
}

async function provisionWorkspace(outputChannel, manualRun = false, forceOpenClawBoot = false) {
  const folders = vscode.workspace.workspaceFolders || [];
  if (folders.length === 0) {
    if (manualRun) {
      vscode.window.showWarningMessage("Free JT7: no workspace folder is open.");
    }
    return;
  }

  const cfg = getConfig();
  const reports = [];

  for (const folder of folders) {
    try {
      const changes = await provisionFolder(folder, cfg);
      reports.push({ folder: folder.name, changes, ok: true });
    } catch (error) {
      reports.push({
        folder: folder.name,
        changes: [],
        ok: false,
        error: error instanceof Error ? error.message : String(error)
      });
    }
  }

  try {
    await syncVsCodeSettings(folders[0], cfg);
  } catch (error) {
    reports.push({
      folder: folders[0].name,
      changes: [],
      ok: false,
      error: error instanceof Error ? error.message : String(error)
    });
  }

  if (forceOpenClawBoot) {
    openClawBootAttempted = false;
  }

  try {
    const openClawResult = await ensureOpenClawGateway(folders[0], cfg, outputChannel);
    if (!openClawResult.ok && cfg.showNotifications) {
      vscode.window.showWarningMessage(
        `Free JT7 OpenClaw: ${openClawResult.error || openClawResult.reason}`
      );
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    outputChannel.appendLine(`[OpenClaw] fatal error: ${message}`);
    if (cfg.showNotifications) {
      vscode.window.showWarningMessage(`Free JT7 OpenClaw error: ${message}`);
    }
  }

  if (!cfg.showNotifications) {
    return;
  }

  const failures = reports.filter((r) => !r.ok);
  const updated = reports.filter((r) => r.ok && r.changes.length > 0);

  if (failures.length > 0) {
    const first = failures[0];
    vscode.window.showErrorMessage(
      `Free JT7: provisioning error in ${first.folder}: ${first.error}`
    );
    return;
  }

  if (updated.length > 0) {
    const details = updated.map((r) => `${r.folder} (${r.changes.join(", ")})`).join("; ");
    vscode.window.showInformationMessage(`Free JT7 active: ${details}`);
    return;
  }

  if (manualRun) {
    vscode.window.showInformationMessage("Free JT7: files already present, nothing changed.");
  }
}

function activate(context) {
  const outputChannel = vscode.window.createOutputChannel("Free JT7 Agent");
  context.subscriptions.push(outputChannel);

  const runCommand = vscode.commands.registerCommand("freeJt7Agent.provisionNow", async () => {
    await provisionWorkspace(outputChannel, true, false);
  });
  context.subscriptions.push(runCommand);

  const openClawCommand = vscode.commands.registerCommand("freeJt7Agent.startOpenClawNow", async () => {
    await provisionWorkspace(outputChannel, true, true);
  });
  context.subscriptions.push(openClawCommand);

  const cfg = getConfig();
  if (cfg.autoProvision) {
    provisionWorkspace(outputChannel, false, false);
  }

  const folderWatcher = vscode.workspace.onDidChangeWorkspaceFolders(() => {
    const current = getConfig();
    if (current.autoProvision) {
      provisionWorkspace(outputChannel, false, false);
    }
  });
  context.subscriptions.push(folderWatcher);

  const configWatcher = vscode.workspace.onDidChangeConfiguration((event) => {
    if (event.affectsConfiguration("freeJt7Agent")) {
      const current = getConfig();
      if (current.autoProvision) {
        provisionWorkspace(outputChannel, false, false);
      }
    }
  });
  context.subscriptions.push(configWatcher);
}

function deactivate() {}

module.exports = {
  activate,
  deactivate
};
