"""Add item groups, customers, sales orders, and reorder points

Revision ID: 0f5723c68fcb
Revises: c0f9e3c371e4
Create Date: 2026-02-11 15:15:54.567202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5723c68fcb'
down_revision = 'c0f9e3c371e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: deleted_at column already exists in movimientos table
    
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reorder_point', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reorder_quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('item_group_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_item_group_id'), ['item_group_id'], unique=False)
        batch_op.create_foreign_key('fk_products_item_group_id', 'item_groups', ['item_group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_products_item_group_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_products_item_group_id'))
        batch_op.drop_column('item_group_id')
        batch_op.drop_column('reorder_quantity')
        batch_op.drop_column('reorder_point')

    # ### end Alembic commands ###
