"""Initial migration with enhanced models

Revision ID: c0f9e3c371e4
Revises: 
Create Date: 2026-02-11 11:12:22.011581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f9e3c371e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracion')
    op.drop_table('usuario')
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_producto_codigo'))
        batch_op.drop_index(batch_op.f('ix_producto_descripcion'))
        batch_op.drop_index(batch_op.f('ix_producto_proveedor_id'))

    op.drop_table('producto')
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proveedor_nombre'))
        batch_op.drop_index(batch_op.f('ix_proveedor_rif'))
        batch_op.drop_index(batch_op.f('ix_proveedor_rubro_material'))

    op.drop_table('proveedor')
    with op.batch_alter_table('cierre_dia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cierre_dia_fecha'))

    op.drop_table('cierre_dia')
    with op.batch_alter_table('movimiento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimiento_cerrado'))
        batch_op.drop_index(batch_op.f('ix_movimiento_fecha'))
        batch_op.drop_index(batch_op.f('ix_movimiento_producto_id'))
        batch_op.drop_index(batch_op.f('ix_movimiento_proveedor_id'))

    op.drop_table('movimiento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimiento',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=10), nullable=False),
    sa.Column('producto_id', sa.INTEGER(), nullable=False),
    sa.Column('cantidad', sa.INTEGER(), nullable=False),
    sa.Column('fecha', sa.DATETIME(), nullable=False),
    sa.Column('proveedor_id', sa.INTEGER(), nullable=True),
    sa.Column('cerrado', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimiento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimiento_proveedor_id'), ['proveedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimiento_producto_id'), ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimiento_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimiento_cerrado'), ['cerrado'], unique=False)

    op.create_table('cierre_dia',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('cerrado_en', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cierre_dia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cierre_dia_fecha'), ['fecha'], unique=1)

    op.create_table('proveedor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('rif', sa.VARCHAR(length=30), nullable=False),
    sa.Column('rubro_material', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proveedor_rubro_material'), ['rubro_material'], unique=False)
        batch_op.create_index(batch_op.f('ix_proveedor_rif'), ['rif'], unique=False)
        batch_op.create_index(batch_op.f('ix_proveedor_nombre'), ['nombre'], unique=False)

    op.create_table('producto',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=200), nullable=False),
    sa.Column('stock', sa.INTEGER(), nullable=True),
    sa.Column('precio_dolares', sa.FLOAT(), nullable=True),
    sa.Column('factor_ajuste', sa.FLOAT(), nullable=True),
    sa.Column('proveedor_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_producto_proveedor_id'), ['proveedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_producto_descripcion'), ['descripcion'], unique=False)
        batch_op.create_index(batch_op.f('ix_producto_codigo'), ['codigo'], unique=1)

    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('password', sa.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('configuracion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tasa_cambiaria', sa.FLOAT(), nullable=False),
    sa.Column('factor_ajuste', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
